name: Gradle Check

on:
  push:
    branches-ignore:
    - develop
    - develop-v4

jobs:
  gradle-check:
    name: Gradle Check
    uses: interlok-tooling/reusable-workflows/.github/workflows/gradle-check.yml@v1.0.0
    secrets:
      NEXUS_REPO_PASSWORD: ${{ secrets.NEXUS_REPO_PASSWORD }}
